import { db } from "./db";
import { airlines } from "@shared/schema";

const airlineData = [
  { code: '6E', name: 'IndiGo', country: 'India' },
  { code: 'AI', name: 'Air India', country: 'India' },
  { code: 'UK', name: 'Vistara', country: 'India' },
  { code: 'G8', name: 'Go First', country: 'India' },
  { code: 'SG', name: 'SpiceJet', country: 'India' },
  { code: 'I5', name: 'AirAsia India', country: 'India' },
  { code: 'EK', name: 'Emirates', country: 'UAE' },
  { code: 'EY', name: 'Etihad Airways', country: 'UAE' },
  { code: 'QR', name: 'Qatar Airways', country: 'Qatar' },
  { code: 'WY', name: 'Oman Air', country: 'Oman' },
  { code: 'G9', name: 'Air Arabia', country: 'UAE' },
  { code: 'FZ', name: 'flydubai', country: 'UAE' },
  { code: 'XY', name: 'flynas', country: 'Saudi Arabia' },
  { code: 'SV', name: 'Saudia', country: 'Saudi Arabia' },
  { code: 'GF', name: 'Gulf Air', country: 'Bahrain' },
  { code: 'KU', name: 'Kuwait Airways', country: 'Kuwait' },
  { code: 'SQ', name: 'Singapore Airlines', country: 'Singapore' },
  { code: 'TG', name: 'Thai Airways', country: 'Thailand' },
  { code: 'MH', name: 'Malaysia Airlines', country: 'Malaysia' },
  { code: 'CX', name: 'Cathay Pacific', country: 'Hong Kong' },
  { code: 'JL', name: 'Japan Airlines', country: 'Japan' },
  { code: 'NH', name: 'All Nippon Airways', country: 'Japan' },
  { code: 'KE', name: 'Korean Air', country: 'South Korea' },
  { code: 'OZ', name: 'Asiana Airlines', country: 'South Korea' },
  { code: 'BR', name: 'EVA Air', country: 'Taiwan' },
  { code: 'CI', name: 'China Airlines', country: 'Taiwan' },
  { code: 'CA', name: 'Air China', country: 'China' },
  { code: 'CZ', name: 'China Southern Airlines', country: 'China' },
  { code: 'MU', name: 'China Eastern Airlines', country: 'China' },
  { code: 'VN', name: 'Vietnam Airlines', country: 'Vietnam' },
  { code: 'VJ', name: 'VietJet Air', country: 'Vietnam' },
  { code: 'PG', name: 'Bangkok Airways', country: 'Thailand' },
  { code: 'FD', name: 'Thai AirAsia', country: 'Thailand' },
  { code: 'SL', name: 'Thai Lion Air', country: 'Thailand' },
  { code: 'VZ', name: 'Thai Vietjet Air', country: 'Thailand' },
  { code: 'UL', icao: 'ALK', name: 'SriLankan Airlines', country: 'Sri Lanka' },
  { code: 'AK', name: 'AirAsia', country: 'Malaysia' },
  { code: 'D7', name: 'AirAsia X', country: 'Malaysia' },
  { code: 'BI', name: 'Royal Brunei Airlines', country: 'Brunei' },
  { code: 'PK', name: 'Pakistan International Airlines', country: 'Pakistan' },
  { code: 'AA', name: 'American Airlines', country: 'USA' },
  { code: 'UA', name: 'United Airlines', country: 'USA' },
  { code: 'DL', name: 'Delta Air Lines', country: 'USA' },
  { code: 'WN', name: 'Southwest Airlines', country: 'USA' },
  { code: 'B6', name: 'JetBlue Airways', country: 'USA' },
  { code: 'AS', name: 'Alaska Airlines', country: 'USA' },
  { code: 'NK', name: 'Spirit Airlines', country: 'USA' },
  { code: 'F9', name: 'Frontier Airlines', country: 'USA' },
  { code: 'G4', name: 'Allegiant Air', country: 'USA' },
  { code: 'HA', name: 'Hawaiian Airlines', country: 'USA' },
  { code: 'BA', name: 'British Airways', country: 'UK' },
  { code: 'LH', name: 'Lufthansa', country: 'Germany' },
  { code: 'AF', name: 'Air France', country: 'France' },
  { code: 'KL', name: 'KLM Royal Dutch Airlines', country: 'Netherlands' },
  { code: 'IB', name: 'Iberia', country: 'Spain' },
  { code: 'AZ', name: 'Alitalia', country: 'Italy' },
  { code: 'LX', name: 'Swiss International Air Lines', country: 'Switzerland' },
  { code: 'OS', name: 'Austrian Airlines', country: 'Austria' },
  { code: 'SN', name: 'Brussels Airlines', country: 'Belgium' },
  { code: 'SK', name: 'Scandinavian Airlines', country: 'Sweden' },
  { code: 'AY', name: 'Finnair', country: 'Finland' },
  { code: 'TP', name: 'TAP Air Portugal', country: 'Portugal' },
  { code: 'EI', name: 'Aer Lingus', country: 'Ireland' },
  { code: 'FR', name: 'Ryanair', country: 'Ireland' },
  { code: 'U2', name: 'easyJet', country: 'UK' },
  { code: 'VY', name: 'Vueling', country: 'Spain' },
  { code: 'W6', name: 'Wizz Air', country: 'Hungary' },
  { code: 'LG', name: 'Luxair', country: 'Luxembourg' },
  { code: 'TK', name: 'Turkish Airlines', country: 'Turkey' },
  { code: 'SU', name: 'Aeroflot', country: 'Russia' },
  { code: 'LO', name: 'LOT Polish Airlines', country: 'Poland' },
  { code: 'OK', name: 'Czech Airlines', country: 'Czech Republic' },
  { code: 'AC', name: 'Air Canada', country: 'Canada' },
  { code: 'WS', name: 'WestJet', country: 'Canada' },
  { code: 'AM', name: 'Aeroméxico', country: 'Mexico' },
  { code: 'Y4', name: 'Volaris', country: 'Mexico' },
  { code: 'VB', name: 'VivaAerobus', country: 'Mexico' },
  { code: 'CM', name: 'Copa Airlines', country: 'Panama' },
  { code: 'AV', name: 'Avianca', country: 'Colombia' },
  { code: 'LA', name: 'LATAM Airlines', country: 'Chile' },
  { code: 'AR', name: 'Aerolineas Argentinas', country: 'Argentina' },
  { code: 'G3', name: 'GOL Linhas Aéreas', country: 'Brazil' },
  { code: 'AD', name: 'Azul Brazilian Airlines', country: 'Brazil' },
  { code: 'QF', name: 'Qantas', country: 'Australia' },
  { code: 'VA', name: 'Virgin Australia', country: 'Australia' },
  { code: 'JQ', name: 'Jetstar Airways', country: 'Australia' },
  { code: 'NZ', name: 'Air New Zealand', country: 'New Zealand' },
  { code: 'FJ', name: 'Fiji Airways', country: 'Fiji' },
  { code: 'ET', name: 'Ethiopian Airlines', country: 'Ethiopia' },
  { code: 'KQ', name: 'Kenya Airways', country: 'Kenya' },
  { code: 'SA', name: 'South African Airways', country: 'South Africa' },
  { code: 'MS', name: 'EgyptAir', country: 'Egypt' },
  { code: 'AT', name: 'Royal Air Maroc', country: 'Morocco' },
  { code: 'UU', name: 'Air Austral', country: 'Réunion' },
  { code: 'MK', name: 'Air Mauritius', country: 'Mauritius' },
  { code: '3U', name: 'Sichuan Airlines', country: 'China' },
  { code: '9W', name: 'Jet Airways', country: 'India' },
  { code: 'XT', name: 'IndiGo', country: 'Indonesia' },
  { code: 'QZ', name: 'Indonesia AirAsia', country: 'Indonesia' },
  { code: 'JT', name: 'Lion Air', country: 'Indonesia' },
  { code: 'GA', name: 'Garuda Indonesia', country: 'Indonesia' },
  { code: 'PR', name: 'Philippine Airlines', country: 'Philippines' },
  { code: '5J', name: 'Cebu Pacific', country: 'Philippines' },
  { code: 'Z2', name: 'AirAsia Philippines', country: 'Philippines' },
  { code: 'HX', name: 'Hong Kong Airlines', country: 'Hong Kong' },
  { code: 'UO', name: 'Hong Kong Express Airways', country: 'Hong Kong' },
  { code: 'HU', name: 'Hainan Airlines', country: 'China' },
  { code: 'SC', name: 'Shandong Airlines', country: 'China' },
  { code: 'MF', name: 'Xiamen Airlines', country: 'China' },
  { code: 'ZH', name: 'Shenzhen Airlines', country: 'China' },
  { code: 'KA', name: 'Dragonair', country: 'Hong Kong' },
  { code: 'PN', name: 'West Air', country: 'China' },
  { code: 'EW', name: 'Eurowings', country: 'Germany' },
  { code: 'VE', name: 'EasyFly', country: 'Colombia' },
  { code: '9C', name: 'Spring Airlines', country: 'China' },
  { code: 'TR', name: 'Scoot', country: 'Singapore' },
  { code: '3K', name: 'Jetstar Asia', country: 'Singapore' },
  { code: 'MI', name: 'SilkAir', country: 'Singapore' },
  { code: 'BG', name: 'Biman Bangladesh Airlines', country: 'Bangladesh' },
  { code: 'BS', name: 'US-Bangla Airlines', country: 'Bangladesh' },
  { code: 'RA', name: 'Nepal Airlines', country: 'Nepal' },
  { code: 'H9', name: 'Himalaya Airlines', country: 'Nepal' },
];

async function seedAirlines() {
  try {
    console.log('Starting to seed airlines...');
    
    for (const airline of airlineData) {
      await db.insert(airlines).values(airline).onConflictDoNothing();
    }
    
    console.log(`Successfully seeded ${airlineData.length} airlines`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding airlines:', error);
    process.exit(1);
  }
}

seedAirlines();
